### ISSUE TITLE
Icons aren't loaded (@nuxt-ui)

### ISSUE THREAD

**Issue by gAlleb** [nuxt/icon#259] opened 2024-09-26 05:50 UTC
Hi there and thanks so much for your work!

Recently I've upgraded `nuxt 3.12.4` to `nuxt 3.13.2`,  `@nuxt/ui@2.18.4` to `@nuxt/ui@2.18.6`, `@tailwindcss/forms@0.5.7, @tailwindcss/typography@0.5.14` to `@tailwindcss/forms@0.5.9, @tailwindcss/typography@0.5.15`. Here are some observations.

Icons stop working on initial site loading (and 50/50% on next loads):

1.  Navigate to webpage (generated by `npm run generate`, incognito mode, no cache): no icons.
2.  Refresh page: sometimes there are icons, sometimes not, sometimes only half of them.

```
The above happens whether one upgrades  to `@nuxt/ui@2.18.6`,`@tailwindcss/forms@0.5.9, @tailwindcss/typography@0.5.15` within `nuxt 3.12.4`.

Or

One upgrades to `nuxt 3.13.2` and `@nuxt/ui@2.18.6`.

Or 

Sometimes when one simply upgrades to `nuxt 3.13.2`.
```

What fixes an issue:

1. Downgrading to `nuxt 3.12.4` with `@nuxt/ui@2.18.4` and `@tailwindcss/forms@0.5.7 @tailwindcss/typography@0.5.14`  fixes an issue.
3. Installiing collections locally (in my case  `@iconify-json/bxl, @iconify-json/heroicons, @iconify-json/heroicons-solid`) and adding:
```ruby
icon: {
clientBundle: {
      scan: true,
      sizeLimitKb: 256, }, },
```

Howewer one question still bothers me. Same `nuxt/ui`. `3.12.4` without the above settings works like a charm, but when updating the above deps barely loads icons. Just changing deps and the necessity of the the above arises. But why?

`3.12.4` and `nuxt/ui@2.18.6` with `@tailwindcss/forms@0.5.9, @tailwindcss/typography@0.5.15` together result in the issue without the above settings (with `nuxt/ui@2.18.4` and `@tailwindcss/forms@0.5.7, @tailwindcss/typography@0.5.14` everything works fine).

`3.13.2` with `nuxt/ui@2.18.6` result in the issue as well (keeping tailwind deps old). And sometimes just upgrading to `3.13.2` results in the issue.

With the minimal amount of site payload (one page - 2-3 icons) - `3.13.2` works fine without the above changes. When full project is in place - icons without the above changes stop working. I'm talking about `npm run generate` with `ssr:true`. `npm run build` works in every case.

Can someone elaborate?

Also you can easily reproduce this behavior (node `v20.17.0)`. 
1. repo: https://github.com/gAlleb/nuxt-om
2. `npm install`.
3.  Run `npm run generate` - all icons work fine.

4. Upgrade `npm install @nuxt/ui@2.18.6 @tailwindcss/forms@0.5.9 @tailwindcss/typography@0.5.15`.

or

5. Upgrade `npx nuxi upgrade` and `npm install @nuxt/ui@2.18.6`

6. Navigate to webpage (generated by `npm run generate`, incognito mode, no cache).

7. Icons won't load without `clientBundle` setting and adding `local collections`.

Thanks!

**Comment by ParsaJR** [comment] 2024-09-26 18:17
I have exactly this problem in my website : www.parsajr.org
https://github.com/ParsaJR/ParsaJR.ORG
Icons are usually not loaded the first time, but if you reload, the problem will likely to be solved. idk what is the problem

**Comment by ParsaJR** [comment] 2024-09-26 18:36
I have exactly this problem. This problem is exist even on the Nuxt.com , unjs docs and... (The problem is not only in Firefox. It is also in Chrome)

![image](https://github.com/user-attachments/assets/3949f5c4-9c1e-4f39-b95c-7757ea7ba99f)

**Comment by tahirmahmudzade** [comment] 2024-10-02 16:09
I'm also having same problem in my production. I'm using Nuxthub / Cloudflare, the same problem happens the first time i open up my production site any solution on this yet ?

> I have exactly the same problem. And looks like this problem also exist even on the Nuxt.com , unjs docs and... (The problem is not only in Firefox. It is also in Chrome)
> 
> ![image](https://private-user-images.githubusercontent.com/98831377/371274208-3949f5c4-9c1e-4f39-b95c-7757ea7ba99f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODU0ODgsIm5iZiI6MTcyNzg4NTE4OCwicGF0aCI6Ii85ODgzMTM3Ny8zNzEyNzQyMDgtMzk0OWY1YzQtOWMxZS00ZjM5LWI5NWMtNzc1N2VhN2JhOTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE2MDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNzU4MDIzNTI1NWZjYTg3MjBkZDY1MmExYzA0NjIxYmI3YWMzZWRiODk5MjY2Zjc1MzA3ZWEwOWYyN2YwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LBqW8ZlnuzDP37IflMPrIG2vDQ_-Bc1txfumAd9shK8)

**Comment by gAlleb** [comment] 2024-10-02 17:33
@tahirmahmudzade
Installing icon collections locally and adding:
```
export default defineNuxtConfig({
  modules: [
    '@nuxt/ui'
  ],
  icon: {
clientBundle: {
 
      scan: true,
 
      sizeLimitKb: 256,
    },
  },
})
```
may fix this.

**Comment by mathieunicolas** [comment] 2024-10-08 17:36
I have the same problem, and I don't like it.
I can't even reproduce the bug, it looks like it's random even when the cache is emptied. I tried few tweaks but I feel a little bit lost in the documentation.

Does someone know why it's happening ? I see no error or problem in the firefox dev tools so I feel like I can't do much.

**Comment by davidekingsss** [comment] 2024-10-12 15:12
similar problem here, I turned down ssr and render with vite-pwa.  when I open my home page directly  icons doesn't load if there is not any trigger, and the icon loading warning in console won't show up everytime. but when I relogin my supabase user my icons render perfectly except the header breadcrumb not rendered at that time point.

**Comment by aligzl** [comment] 2024-10-12 21:41
same problem, even in the nuxt-ui website or offical nuxt website or any nuxt websites. Seems like general issue. I hope will be fixed soon.

**Comment by tahirmahmudzade** [comment] 2024-10-12 21:43
> @tahirmahmudzade
> Installing icon collections locally and adding:
> ```
> export default defineNuxtConfig({
>   modules: [
>     '@nuxt/ui'
>   ],
>   icon: {
> clientBundle: {
>  
>       scan: true,
>  
>       sizeLimitKb: 256,
>     },
>   },
> })
> ```
> may fix this.

This worked well, thanks a lot!

**Comment by danielroe** [comment] 2024-10-13 19:38
cc: @benjamincanac @antfu 

got a few reports on twitter: https://twitter.com/kregenrek/status/1845546610731745296

**Comment by gt-anthony** [comment] 2024-10-28 17:06
Just chiming in that my team is continuing to have issues here, none of the "fixes" listed above work on our end (hosting on Netlify).

Half of our icons don't load on new builds or when the url hasn't been viewed in a while. Then, after a refresh they usually show up. It also seems to happen to the same set of our icons every time — some use the `dynamic` prop, others don't, both instances have issues where the icon won't load at first.

We've tried downgrading packages, and applying the config updates listed here, but unfortunately nothing fixes it for us. We use Nuxt Icon as part of using Nuxt UI Pro.

Does anyone have a different solution/workaround here? We're holding off on a public reveal of our project until this is resolved, and I'd prefer to use Nuxt Icon if possible...

**Comment by mathieunicolas** [comment] 2024-10-28 17:15
Adding some data
The issue still happens on a fresh Nuxt UI alpha install, and on the ui3 website as well.

**Comment by JhumanJ** [comment] 2024-11-04 14:20
Same issue for us but only locally

**Comment by antfu** [comment] 2024-11-06 05:53
> repo: https://github.com/gAlleb/nuxt-om

I am not able to reproduce on this repo with the latest `@nuxt/ui` and `@nuxt/icon`

Can anyone send a minimal reproduction? Thanks!

**Comment by lovatom** [comment] 2024-11-06 11:30
Same issue on my project in prod. Icons are loading properly in local but once in prod, the icon are showing up on 50% of the time, unless user force reload the page. Already downloaded the icons to my project and added` "@nuxt/icon"` to my config

**Comment by antfu** [comment] 2024-11-10 11:11
After a deep digging, I found out this was because, in certain mono repo setups, there will be two versions of `@iconify/vue` that get bundled to the client side, causing the client bundle not to register to the correct instance. [v1.7.2](https://github.com/nuxt/icon/releases/tag/v1.7.2) should fix that by including a dedupe config by default - let me know if it helps!

**Comment by gAlleb** [comment] 2024-11-10 11:46
Thanks @antfu. It seems to work! I've removed `clientBundle` with icon collections, installed `1.7.2` alongside `nuxt/ui` - icons are loaded. First it gave me `timeout warnings`, but after removing `node_modules` and reinstalling - no warnings, icons are loaded. Thanks!

```
  "devDependencies": {
    "@nuxt/content": "^2.13.4",
    "@nuxt/icon": "^1.7.2",
    "@nuxt/image": "^1.7.0",
    "@nuxt/ui": "^2.19.1",
    "@nuxtjs/i18n": "^9.0.0",
    "@pinia/nuxt": "^0.7.0",
    "@tailwindcss/aspect-ratio": "^0.4.2",
    "@tailwindcss/forms": "^0.5.9",
    "@tailwindcss/typography": "^0.5.15",
    "@types/node": "^22.9.0",
    "nuxt": "^3.14.159",
   ...
```

**Closed** 2024-11-10 14:42 UTC

**Comment by dany68** [comment] 2024-11-11 10:51
Hi,

Thanks @antfu for your work. It seems the error still persist. I deleted the node_modules, updated all the dependencies (nuxt, icon...) to the latests, and also tried the clientBundle options described above.

For some reasons sometimes the icons don't appear (very randomly) on production server. Locally with npm run dev there is no problem.

**Comment by onurusluca** [comment] 2024-11-11 13:48
Still having this problem. Just like what @dany68 said. Exactly the same. Very random but it happens both when provider is server or iconify.

**Comment by CodyBontecou** [comment] 2024-11-11 15:51
Unfortunately, I am seeing the same thing as @dany68. This is using v1.7.2.

**Comment by onurusluca** [comment] 2024-11-13 10:19
Having the same problem too. But randomly, sometimes. Of course mostly after new deployment and on initial load.

**Comment by hoachnt** [comment] 2024-11-14 04:29
> Having the same problem too. But randomly, sometimes. Of course mostly after new deployment and on initial load.

Yeah, I still don't understand when the icons are rendering and when they aren't

**Comment by antfu** [comment] 2024-11-14 04:31
If anyone still encounter this, I'd be appreciated if you can create a new issue with a minimal reproduction so I can have a deeper look. Thanks!

**Comment by hoachnt** [comment] 2024-11-14 05:12
> If anyone still encounter this, I'd be appreciated if you can create a new issue with a minimal reproduction so I can have a deeper look. Thanks!

Oh yeah, it works now after updating the dependency

**Comment by dany68** [comment] 2024-11-14 14:17
I’m still experiencing the issue despite having all dependencies up to date: @nuxt/icon@1.7.5 and nuxt@3.14.159. When inspecting the missing icons, I see that the <svg> tags are present but contain no path attributes.

@antfu I can make a new issue and reproduction today, but since it appears only on production builds i'm not sure i'll be able to reproduce the error. My site is in staging but i can give you access (there is basic auth) if you need to inspect.

**Comment by IzakJackson** [comment] 2024-11-20 13:13
I also face this issue on Nuxt ui3, specifically when caching with ISR in production.

My production site throws these errors and does not load the icons:

```
[Icon] failed to load icon `heroicons:gift-top-solid` rrweb-plugin-console-record.js:2447:17
[Icon] failed to load icon `heroicons:sun-solid` rrweb-plugin-console-record.js:2447:17
[Icon] failed to load icon `heroicons:book-open-solid` rrweb-plugin-console-record.js:2447:17
[Icon] failed to load icon `heroicons:rectangle-group-solid` 3 rrweb-plugin-console-record.js:2447:17
[Icon] failed to load icon `heroicons:cake-solid` rrweb-plugin-console-record.js:2447:17
[Icon] failed to load icon `heroicons:users-solid` rrweb-plugin-console-record.js:2447:17
[Icon] failed to load icon `heroicons:academic-cap-solid` rrweb-plugin-console-record.js:2447:17
```

My preview site that has no ISR/caching throws no errors.

I have installed the icon pack dependencies. I'm on the latest version of Nuxt ui3. I've tried clearing my vercel and broswer cache, and I've added the below to my Nuxt Config:

```
icon: {
clientBundle: {
 
      scan: true,
 
      sizeLimitKb: 256,
    },
  },
```

**Comment by JhumanJ** [comment] 2024-11-20 16:36
> If anyone still encounter this, I'd be appreciated if you can create a new issue with a minimal reproduction so I can have a deeper look. Thanks!

Hey Antfu, I struggled to consistently reproduce this, but I found that via our docker setup the issue is always here, sorry if I don't have a simpler reproduction for now. Instructions [are here](https://docs.opnform.com/deployment/docker), but here's a summary:
- `git clone https://github.com/JhumanJ/OpnForm.git`
- `cd OpnForm`
- `./scripts/setup-env.sh --docker` (setup env files)
- `docker-compose up -d` (make sure port 80 is clear)
- Open localhost, login with `admin@opnform.com` / `password`
- Click create a form 
- Then you can see all icons error
![Image](https://github.com/user-attachments/assets/1c96a0ab-d0c9-4f9d-8735-9f6281d416f7)

**Comment by antfu** [comment] 2024-11-20 16:53
Please create a new issue for us to track please, we don't usually look at closed issues.

I am locking this thread just in case. Thanks.
