### ISSUE TITLE
500 [vite-node] [ERR_LOAD_URL] @iconify/vue

### ISSUE THREAD

**Issue by RakuThe1** [nuxt/icon#234] opened 2024-08-11 00:46 UTC
After updating from the "nuxt-icon" to "@nuxt/icon", I am getting an unknown "500 [vite-node] [ERR_LOAD_URL] @iconify/vue" error.

Can someone please help me how to fix it?

Everything was working fine before upgrading. I tried to reinstall all the node modules as well but the error is still there :(

![image](https://github.com/user-attachments/assets/9c53e4fe-2260-454a-9394-03ee8d7ce05b)

**Comment by RakuThe1** [comment] 2024-08-12 01:43
@antfu Can you please help?

**Comment by antfu** [comment] 2024-08-12 09:55
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-12 09:55 UTC

**Comment by FlorianWerndl** [comment] 2024-08-14 08:47
@RakuThe1 try `npm install --save-dev @iconify/vue`

**Comment by RakuThe1** [comment] 2024-08-14 09:33
> @RakuThe1 try `npm install --save-dev @iconify/vue`

It worked. Thank u soo much :)

**Comment by cyrilf** [comment] 2024-09-12 12:16
I had the same issue.

To solve it, I simply moved my `@nuxt/icon` from the `devDependencies` into the `dependecies` in my `package.json` by doing:
`npm remove @nuxt/icon` and then `npm install --save  @nuxt/icon`.
Now my `dependencies` looks like this:
```
"dependencies": {
    // ...
    "@nuxt/icon": "^1.5.1"
    "nuxt": "^3.13.1"
    "vue": "^3.5.1",
    // ...
  },
```

And now my `package-lock.json` correctly contains a `"node_modules/@iconify/vue"` key, before it was: `"node_modules/@nuxt/icon/node_modules/@iconify/vue"`.
