### ISSUE TITLE
icon x ag-grid

### ISSUE THREAD

**Issue by mbertolani** [nuxt/icon#231] opened 2024-08-03 18:35 UTC
Hi,
I'm using ag-grid (https://www.ag-grid.com/) and after v2.18.0 (nuxt-ui) the icons aren't showing.
I get this warning message:

[Vue warn]: Component <NuxtIcon>: setup function returned a promise, but no <Suspense> boundary was found in the parent component tree. A component with async setup() must be nested in a <Suspense> in order to be rendered. 
  at <NuxtIcon name="i-healthicons-hospital" mode=null size=null  ... > 
  at <Icon key=0 name="i-healthicons-hospital" class="flex-shrink-0 w-5 h-5 relative text-gray-400 dark:text-gray-500 group-hover:text-gray-700 dark:group-hover:text-gray-200" > 
  at <Link ref_for=true class="group relative flex items-center gap-1.5 focus:outline-none focus-visible:outline-none dark:focus-visible:outline-none focus-visible:before:ring-inset focus-visible:before:ring-1 focus-visible:before:ring-primary-500 dark:focus-visible:before:ring-primary-400 before:absolute before:inset-px before:rounded-md disabled:cursor-not-allowed disabled:opacity-75 px-2.5 py-1.5 w-full focus-visible:ring-inset focus-visible:ring-2 focus-visible:ring-primary-500 dark:focus-visible:ring-primary-400 rounded-md font-medium text-sm" active-class="text-gray-900 dark:text-white before:bg-gray-100 dark:before:bg-gray-800"  ... > 

    "ag-grid-vue3": "^32.0.2",
    "nuxt": "^3.12.4",
    "@nuxt/fonts": "^0.7.1",
    "@nuxt/icon": "^1.4.5",
    "@nuxt/image": "^1.7.0",
    "@nuxt/ui": "^2.17.0",
    "@nuxt/ui-pro": "^1.3.1",

**Comment by antfu** [comment] 2024-08-27 10:43
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-27 10:43 UTC
