### ISSUE TITLE
custom local collections do not accept props like color

### ISSUE THREAD

**Issue by rowild** [nuxt/icon#307] opened 2024-11-22 22:59 UTC
My folder structure looks the same as it is described in the documentation (https://nuxt.com/modules/icon#custom-local-collections):

`assets/my-icons/photogrammetry.svg`

However, I load content from a json file:

```json
{
    "data": {
        "0": {
            "title": "Video- & Photography",
            "icon": "my-icon:photogrammetry",
            "iconColor": "text-cyan-400",
            [...]
        },
```

... into the component:

```vue
<script setup>
import services from "/public/jsons/services.json"
...
</script>

<template>
[...]
 <div class="[ card ] absolute" :class="service.iconColor">
    <Icon :name="service.icon" :color="service.iconColor" size="10rem" />
 </div>
[...]
</template>
```

The icon (which is and remains black) does not accept any color, while any standard implementation (icon from a downloaded icon set like mdi) does indeed change the color of an icon.

(Just in case this is not an error: What kind of "treatment" do I have to apply to make my icon accept color?)

**Comment by antfu** [comment] 2024-11-23 07:53
`color` is not a prop that `<Icon` accepts. You need to use `class` or `style` to change the `color` value in CSS. Meanwhile you need to set color to `currentColor` in your svg.

**Comment by antfu** [comment] 2024-11-23 07:53
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-11-23 07:53 UTC

**Comment by rowild** [comment] 2024-11-23 10:04
This is from the Nuxt/Icon documentation:

When using an icon from Iconify, an <span> or <svg> will be created based on the rendering mode, you can give [all the attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute) of the native element.

And this from W3C:

https://www.w3.org/TR/SVG2/styling.html#ElementSpecificStyling

Why would `<Icon ` not support the `class` attribute??? (...which it does, just no with CustomIcons or with my own icons as explained above.) I really wonder what I am misunderstanding here?

**Comment by rowild** [comment] 2024-11-23 10:19
I see the error I made, using `color` instead of `class`. How stupid of me! Sorry for the bother and thank you for the quick and helpful answer!
