### ISSUE TITLE
[Icon] Collection [ any Collection name ] is not found locally , while i installed @iconify/json

### ISSUE THREAD

**Issue by taymakz** [nuxt/icon#194] opened 2024-07-08 15:06 UTC
i get icon is not found locally , render mode : css

![image](https://github.com/nuxt/icon/assets/71381670/dc1de179-edd5-4d3d-9116-893ad623da01)

**Comment by deep-project** [comment] 2024-07-09 08:46
same

**Comment by antfu** [comment] 2024-07-18 17:01
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by taymakz** [comment] 2024-07-18 17:47
i created a repo ,  just run dev, and check terminal you see the problem, sir
The problem is that I downloaded the whole Icon collection( @iconify/json ) , but it seems that we have to download one by one like 
install carbon collection, logos collection

**Closed** 2024-07-20 22:05 UTC
