### ISSUE TITLE
[Bug] Icon cannot be displayed when used with nuxt-ui

### ISSUE THREAD

**Issue by zzy-life** [nuxt/icon#221] opened 2024-07-29 07:05 UTC
url("data:image/svg+xml,%3Csvg xmlns='https://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath d='M20 6c0-2.168-3.663-4-8-4S4 3.832 4 6v2c0 2.168 3.663 4 8 4s8-1.832 8-4V6zm-8 13c-4.337 0-8-1.832-8-4v3c0 2.168 3.663 4 8 4s8-1.832 8-4v-3c0 2.168-3.663 4-8 4z' fill='black'/%3E%3Cpath d='M20 10c0 2.168-3.663 4-8 4s-8-1.832-8-4v3c0 2.168 3.663 4 8 4s8-1.832 8-4v-3z' fill='black'/%3E%3C/svg%3E")

The test environment is fine, but the production environment will not be able to display the icon. If I change the https in xmlns to http, it will display.

![image](https://github.com/user-attachments/assets/0df3c38c-7cca-47ae-a101-23bb71c5945b)

**Comment by zzy-life** [comment] 2024-07-29 07:06
![image](https://github.com/user-attachments/assets/822a1f30-ddaa-448a-8027-6310567c65f5)
Why does it automatically convert to https?
0.6.8 is normal

**Comment by zzy-life** [comment] 2024-07-29 14:37
Finally fixed this....setting mode to svg solved the problem, but I guess this is not the root solution

**Comment by antfu** [comment] 2024-07-29 16:11
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-29 16:11 UTC

**Comment by zzy-life** [comment] 2024-08-11 05:47
#212 #228 
Similar problem, this should be taken seriously, it is broken in 1.0.0
