### ISSUE TITLE
After packaging, I don't know why it points to https://api.iconify.design/icon.json. This will return 404, causing the website icon svg to not come out. The following is my nuxt.config configuration. I don't want to request https://api.iconify.design/icon.json because it is my local icon.

### ISSUE THREAD

**Issue by wsw2000** [nuxt/icon#258] opened 2024-09-22 04:00 UTC
![image](https://github.com/user-attachments/assets/6c36719d-c382-4751-9ab7-dc5e27f062bd)
![image](https://github.com/user-attachments/assets/4a062ae0-4582-468d-9d82-a83bf7a256d9)
![image](https://github.com/user-attachments/assets/d3ae66ee-9408-495f-92e0-1773791ca17c)
![image](https://github.com/user-attachments/assets/ff6f18f5-9fb5-4d2e-b694-3d1089225731)

这是下面遇到的问题：
![image](https://github.com/user-attachments/assets/7c4501ba-f1db-45fe-9deb-1e51f323dfc3)
![image](https://github.com/user-attachments/assets/4387c4df-4aaa-4732-845c-c095412615e6)

**Comment by antfu** [comment] 2024-09-22 21:35
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-09-22 21:35 UTC
