### ISSUE TITLE
Some icons don't load sometimes

### ISSUE THREAD

**Issue by thomasbnt** [nuxt/icon#312] opened 2024-12-06 12:30 UTC
Hello, you can see directly here at [thomasbnt.dev](https://thomasbnt.dev). Some icons don't load sometimes, it's full random when we load the page. 

```json
devDependencies": {
    "@iconify-json/ant-design": "^1.2.1",
    "@iconify-json/bi": "^1.2.0",
    "@iconify-json/fa6-brands": "^1.2.0",
    "@iconify-json/line-md": "^1.2.1",
    "@iconify-json/lucide": "^1.2.4",
    "@iconify-json/mdi": "^1.2.0",
    "@iconify-json/mingcute": "^1.2.0",
    "@iconify-json/ri": "^1.2.0",
    "@iconify-json/simple-icons": "^1.2.3",
    "@iconify-json/tabler": "^1.2.3",
    "@iconify/vue": "^4.1.2",
    "@nuxt/content": "2.13.2",
    "@nuxt/devtools": "^1.4.2",
    "@nuxt/eslint": "^0.5.7",
    "@nuxt/eslint-config": "^0.5.7",
    "@nuxt/icon": "^1.5.1",
    "@nuxt/image": "^1.8.0",
    "@nuxthq/studio": "^2.1.1",
    "@nuxtjs/i18n": "^8.5.4",
    "@types/node": "^22.5.5",
    "@types/rss": "^0.0.32",
    "@vueuse/core": "^11.1.0",
    "@vueuse/motion": "^2.2.5",
    "dayjs": "^1.11.13",
    "eslint": "^9.10.0",
    "nuxt": "^3.13.2",
    "nuxt-gtag": "^3.0.1",
    "remark-breaks": "^4.0.0",
    "remark-directive-rehype": "^0.4.2",
    "sass": "^1.79.2"
  },
```

**Comment by antfu** [comment] 2024-12-10 07:11
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-12-10 07:11 UTC
