### ISSUE TITLE
Some SVG cannot be displayed

### ISSUE THREAD

**Issue by zhonguanping** [nuxt/icon#242] opened 2024-08-26 03:14 UTC
![brand-Auman](https://github.com/user-attachments/assets/a864645c-c0eb-4581-885e-effce6bc8ca9)
https://github.com/user-attachments/assets/a864645c-c0eb-4581-885e-effce6bc8ca9
This SVG file cannot be displayed
But using this module（ https://nuxt.com.cn/modules/icons ）Can display normally

**Comment by antfu** [comment] 2024-08-27 10:33
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-27 10:33 UTC
