### ISSUE TITLE
Render blocking CSS WPO Core Vitals

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/icon#155] opened 2024-04-25 10:38 UTC
This css blocks the render of page... Why not this resource with async and defer?

![image](https://github.com/nuxt-modules/icon/assets/77386602/525f8470-9179-4a46-8d47-9448d198cd97)

**Comment by antfu** [comment] 2024-07-18 22:45
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-18 22:45 UTC
