### ISSUE TITLE
v1.4.0 does not generate with ssr:false

### ISSUE THREAD

**Issue by JohnCampionJr** [nuxt/icon#227] opened 2024-07-31 18:29 UTC
With `ssr:false`

v1.3.0 works fine

v 1.4.0 Generates this error:
```
Error: r] Could not compile template `nuxt-icon-client-bundle.mjs`.
Error: r] The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at isAbsolute (node:path:1156:5)
    at loadCustomCollection (/home/runner/work/myapp/myapp/src/frontend/node_modules/.pnpm/@nuxt+icon@1.4.3/node_modules/@nuxt/icon/dist/module.mjs:394:15)
    at /home/runner/work/myapp/myapp/src/frontend/node_modules/.pnpm/@nuxt+icon@1.4.3/node_modules/@nuxt/icon/dist/module.mjs:542:57
    at Array.map (<anonymous>)
    at Object.getContents (/home/runner/work/myapp/myapp/src/frontend/node_modules/.pnpm/@nuxt+icon@1.4.3/node_modules/@nuxt/icon/dist/module.mjs:542:37)
    at compileTemplate (/home/runner/work/myapp/myapp/src/frontend/node_modules/.pnpm/@nuxt+kit@3.12.2/node_modules/@nuxt/kit/dist/index.mjs:2066:23)
    at processTemplate (/home/runner/work/myapp/myapp/src/frontend/node_modules/.pnpm/nuxt@3.12.2/node_modules/nuxt/dist/index.mjs:5057:28)
    at Array.map (<anonymous>)
    at generateApp (/home/runner/work/myapp/myapp/src/frontend/node_modules/.pnpm/nuxt@3.12.2/node_modules/nuxt/dist/index.mjs:5084:50)
    at async _applyPromised (/home/runner/work/myapp/myapp/src/frontend/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:54:10)
```

**Comment by antfu** [comment] 2024-07-31 21:40
I could not reproduce, can you create a minimal reproduction? Thanks

**Comment by antfu** [comment] 2024-07-31 21:41
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-31 21:41 UTC

**Comment by JohnCampionJr** [comment] 2024-08-01 13:08
OK, I'll try to put one together.
