### ISSUE TITLE
Seems like @nuxt/icon doesn't understand other language in files name in local icon collection

### ISSUE THREAD

**Issue by ztxone** [nuxt/icon#201] opened 2024-07-14 00:25 UTC
So in my case in nuxt.config.ts i described custom collection 
icon: {
   customCollections: [
    {
      prefix: 'elfi',
      dir: './assets/icons'
    },
   ],
}

if in my directory lies files with EN names - all works fine
if i put there file with cyrillic (for ex RU) name - the nuxt even can't start properly with "npm run dev" - blank screen with no errors

and one else thing - if i make some changes in folder with icons - i need to terminate nuxt and run again "npm run dev" to activate changes

**Comment by antfu** [comment] 2024-07-15 15:41
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-15 15:41 UTC

**Comment by ztxone** [comment] 2024-07-16 13:30
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

Here is fresh install of nuxt with @nuxt/ui and @nuxt/icon modules
I've prepared structure with calling icons with different variants.
And there are 2 svg icons in the asset/icons folder - with EN-letters name and with RU-letters name

So there are two questions:

1st:  when i'm uncommenting call with RU-named icon - the nuxt app won't start properly at all - seems like a bug

2nd: if i make some changes to filename or folder structure (simply add/remove/rename any icon in asset folder) - it doesn't trigger the hmr or reruning active app - i need to manually restart nuxt app with "npm run dev" command. Is it ok?


https://github.com/ztxone/nuxt-issue
