### ISSUE TITLE
Slow module @nuxt/icon took 12455.29ms to setup.  

### ISSUE THREAD

**Issue by sgween** [nuxt/icon#229] opened 2024-08-03 12:41 UTC
Continually get:

"**WARN** Slow module @nuxt/icon took [XXXX]ms to setup"
 
 Time varies but message persists and can't get rid of it.

**Comment by antfu** [comment] 2024-08-27 10:42
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-27 10:42 UTC
