### ISSUE TITLE
Package import specifier "#internal/nitro/virtual/app-config" is not defined

### ISSUE THREAD

**Issue by kogratte** [nuxt/icon#204] opened 2024-07-16 15:24 UTC
### Environment

npx nuxi info
Working directory: /Users/nico/sources/empty-app                                                                                                          11:10:13 AM
Nuxt project info: (copied to clipboard)                                                                                                                  11:10:13 AM

------------------------------
- Operating System: Darwin
- Node Version:     v22.3.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      compatibilityDate, devtools, modules
- Runtime Modules:  @nuxt/icon@1.0.0
- Build Modules:    -
------------------------------

### Reproduction

I started from an empty app, then add a single nuxt module.

This module has been spotted in another context as being the source of the exact same issue. The link below is a reproduction context, with both dev and production run logs. It also provides the .output I got after using `npx nuxi build`.

https://github.com/kogratte/nuxt-icons-issue

### Describe the bug

Working on another project, I have an issue `Package import specifier "#internal/nitro/virtual/app-config" is not defined in package /Users/nico/sources/empty-app/node_modules/nitropack/package.json imported from /Users/nico/sources/empty-app/node_modules/nitropack/dist/runtime/config.mjs`.

As we were not aware of the origin, we tried to deep dive to finaly use a "remove and try" method. We finally spotted that the simple presence of this module (nuxt/icons) in our reusable layer what at the origin of the issue. As soon as we remove it, things goes well.

We've been wondering if it could be due to a bad combination, and created the linked repository.

`npx nuxi dev` => Ends with error.
`npx nuxi build` => OK.
     `node .output/server/index.mj` => Same error as `nuxi dev`.

### Logs

```shell-script
See .log files in the linked repository.
```

**Comment by ReWWeR** [comment] 2024-07-25 10:58
Got the same issue here

**Comment by ReWWeR** [comment] 2024-07-25 11:29
Coincidence or not, but when I updated Nuxt to 3.12.4, everything built without errors.

**Comment by tguelcan** [comment] 2024-08-03 13:50
I had the same problem. After deleting .nuxt and node_modules and reinstalling node_modules, it was gone

**Comment by BayBreezy** [comment] 2024-08-05 04:36
Hey. I am experiencing this issue. When developing a module, if I add this module to the playground, the playground will not start.

Here is a minimal reproduction link: https://stackblitz.com/edit/nuxt-starter-xqmvk1?file=playground/nuxt.config.ts

If you remove the comment in front of this module in the `nuxt.config` file within the playground folder, you will get this error. I get this error when adding the content module to playground as well.

Is there any workaround for this at the moment?

**Comment by Anton-Plagemann** [comment] 2024-08-09 10:04
Also got into this error just by using `npx nuxi@latest init -t ui` followed by `npm run dev`

**Comment by Anton-Plagemann** [comment] 2024-08-09 10:59
Locking the `nitropack` version to `2.9.6` (from `2.9.7`) fixed the error for me.
I did this using the `override`-section in `package.json`:

```json
  "overrides": {
    "nitropack": "2.9.6"
  }
```

Similar issues haven been seen at other modules:
- https://github.com/nuxt/content/issues/2736
- https://github.com/getsentry/sentry-javascript/pull/13183

**Comment by BayBreezy** [comment] 2024-08-09 20:04
@Anton-Plagemann thank you for the patch. I tried it in the reproduction i posted above your comment and it worked!
I added the override to the playground's package.json file. Appreciate it
Next is to try it locally and then try deploying to Netlify

**Comment by Anton-Plagemann** [comment] 2024-08-09 20:48
@pi0 Seems like the release of nitro 2.9.7 did break something, especially for clean setups (e.g. `npx nuxi@latest init -t ui` or `npx nuxi@latest init docs -t content`) or module authors (see [my comment](https://github.com/nuxt/icon/issues/204#issuecomment-2277693315)). It would be highly appreciated if you could take a look at this! 🙏

**Comment by BayBreezy** [comment] 2024-08-10 13:27
@Anton-Plagemann for local dev, i had to lock nitropack at v2.9.5 for things to work

**Comment by ReWWeR** [comment] 2024-08-10 14:59
@Anton-Plagemann I've got it working with nitro 2.9.7

**Comment by taogaetz** [comment] 2024-08-12 17:07
hi folks, same issue, I think this is related:

https://github.com/directus-labs/agency-os/issues/109

**Comment by rgenge** [comment] 2024-08-20 20:48
Hi folks, something that fixed here is stop using pnpm. If I run pnpm install and later on I run the server I got this error, if I just run npm install and then npm run dev it runs smootly. But it needs to be ran in a new repo in which pnpm was never user.

**Comment by XHZ360** [comment] 2024-08-21 05:21
I try to install nuxt/icon in this project rather than only install in the reusable layer,  and then it works.

**Comment by JhumanJ** [comment] 2024-08-22 11:13
Same issue - I haven't managed to fix...

**Comment by fnacarellidev** [comment] 2024-08-23 14:34
Here too.

**Comment by paul908** [comment] 2024-08-23 15:34
Here too.

**Comment by JhumanJ** [comment] 2024-08-26 10:00
I tried 
```
"overrides": {
    "nitropack": "2.9.6"
  }
```
and also directly `npm install nitropack@2.9.6` but neither worked...

**Comment by JhumanJ** [comment] 2024-08-26 12:21
Steps to reproduce:
- Clone https://github.com/JhumanJ/opnform
- `cd client`
- `npm install` 
- `npm run build`: should be successful
- `node .output/server/index.mjs`

Which gives this: 
```
node .output/server/index.mjs  
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#internal/nitro/virtual/app-config" is not defined in package /Users/jhumanj/Documents/coding/laravel-projects/notiontools/client/.output/server/node_modules/nitropack/package.json imported from /Users/jhumanj/Documents/coding/laravel-projects/notiontools/client/.output/server/node_modules/nitropack/dist/runtime/config.mjs
    at new NodeError (node:internal/errors:405:5)
    at importNotDefined (node:internal/modules/esm/resolve:353:10)
    at packageImportsResolve (node:internal/modules/esm/resolve:803:9)
    at moduleResolve (node:internal/modules/esm/resolve:967:16)
    at defaultResolve (node:internal/modules/esm/resolve:1193:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_PACKAGE_IMPORT_NOT_DEFINED'
}

Node.js v18.19.0
```

What I tried: 
- setting nitropack override version
- installing nitropack dependency
- Updating versions of all depencies (nuxt, vue etc)
- Different versions of node

I'm not sure if this is related, but at some point while trying to update all dependencies, i obtained the following error running the built server:
```
node .output/server/index.mjs 
Listening on http://[::]:3000
[nuxt] [request error] [unhandled] [500] Cannot find module '/Users/jhumanj/Documents/coding/laravel-projects/OpnForm/client/.output/server/node_modules/vue/server-renderer/index.mjs' imported from /Users/jhumanj/Documents/coding/laravel-projects/OpnForm/client/.output/server/chunks/routes/renderer.mjs
  at new NodeError (node:internal/errors:405:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:327:11)  
  at moduleResolve (node:internal/modules/esm/resolve:980:10)  
  at defaultResolve (node:internal/modules/esm/resolve:1193:11)  
  at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)  
  at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)  
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)  
  at link (node:internal/modules/esm/module_job:75:36)
  ```

**Comment by BayBreezy** [comment] 2024-09-02 10:44
No real fix for this as yet? The overrides trick isnt working anymore

**Comment by antfu** [comment] 2024-09-02 15:29
I tried to investigate but haven't had a clue yet. My assumption is that it might be caused by some transitive dependencies updates and introduced breakage that neither Nitro nor Nuxt Icon. But nothing confirmed yet.

**Comment by BayBreezy** [comment] 2024-09-02 15:45
Thanks @antfu .
Have you experienced the problem locally?
I can create meaningful docs for even a brand new module. The playground won't start if either the content module/icon module is in it.

**Comment by pi0** [comment] 2024-09-02 16:13
If you can make a more minimal reproduction i would be happy to investigate it. It is most likely a module tries to import from `#internal/nitro` (or worst `#internal/nitro/*`) but they should instead import from `nitropack/runtime` or better `#imports`.

**Comment by BayBreezy** [comment] 2024-09-02 16:49
Hey @pi0 , I do have a minimal repo setup here: https://stackblitz.com/edit/nuxt-starter-xqmvk1?file=playground/nuxt.config.ts

**Comment by pi0** [comment] 2024-09-03 09:27
Thanks for the reproductions. 

~> https://github.com/nuxt/icon/pull/249

**Closed** 2024-09-03 19:36 UTC

**Comment by BayBreezy** [comment] 2024-09-04 02:37
Thanks for the fix. 
Now to make a report in the content module 🤣

**Comment by mlkt** [comment] 2024-10-13 04:08
@antfu What is the root cause? In my case, I can't avoid it with `#imports` .
```ts
import { useRequestBody } from "nitropack/runtime/utils";
```

It's not work:
```ts
import { useRequestBody } from "#imports";
```

`useRequestBody`  is just an example, in fact, I still need to call other functions.

**Comment by jonasfroeller** [comment] 2024-10-29 16:50
I just came back to one of my projects after 2 weeks and I now get this out of nowhere.

```
[17:48:32]  ERROR  [worker reload] [worker init] Package import specifier "#internal/nitro/virtual/app-config" is not defined in package D:\xxx\node_modules\nitropack\package.json imported from D:\xxx\node_modules\nitropack\dist\runtime\config.mjs

  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
  at new NodeError (node:internal/errors:405:5)
  at importNotDefined (node:internal/modules/esm/resolve:353:10)
  at packageImportsResolve (node:internal/modules/esm/resolve:803:9)
  at moduleResolve (node:internal/modules/esm/resolve:967:16)
  at defaultResolve (node:internal/modules/esm/resolve:1193:11)
  at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
  at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
  at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by RoyeL12** [comment] 2025-02-04 06:18
![Image](https://github.com/user-attachments/assets/0ab51328-1684-4e40-88f1-630cc92483f0)

For me i had an incorrect import used on my server, i just removed this import line and everything worked again
