### ISSUE TITLE
timeout warning

### ISSUE THREAD

**Issue by lammerfalcon** [nuxt/icon#278] opened 2024-10-11 09:08 UTC
![Image](https://github.com/user-attachments/assets/978a6c9a-8672-41a8-af12-1ba6918a8796)
started to receive this warnings, what should i check?

**Comment by danperks** [comment] 2024-10-17 14:48
I get these, even though the packs containing the icons are installed locally and have visibly loaded on the client before the error shows in the server log. Suggests the SSR is failing to load the icons?

**Comment by mthmcalixto** [comment] 2024-10-21 01:50
same problem!

**Comment by Timur3222** [comment] 2024-10-23 07:49
I have the same. Fix it please.

**Comment by buff** [comment] 2024-11-21 17:47
I am getting this warning and the icons are not displayed on my page.
It has been like this for a few iterations of nuxt.ui. As you can see I have imported the icon sets that I am using and when nuxt builds it identifies that I have a local server environment.
I have ssr enabled but on some of my routes I have ssr: false
I have tried to use the icon: {
    provider: 'server',
  }, setting.
I don't really know what else to do to either troubleshoot or change in my configuration.

Node Version: v20.17.0
Nuxt Version: @3.14.1592
Nuxt-ui version: 2.19.2
Package Manager: npm@10.9.0
iconify-json/carbon@1.2.4
iconify-json/ci@1.2.1
iconify-json/fa6-solid@1.2.2
iconify-json/fluent@1.2.7
iconify-json/heroicons@1.2.1
iconify-json/ic@1.2.1
iconify-json/ion@1.2.1
iconify-json/material-symbols@1.2.7
iconify-json/mdi@1.2.1
iconify-json/pajamas@1.2.4
iconify-json/streamline@1.2.1
iconify-json/svg-spinners@1.2.1
iconify-json/tabler@1.2.8
iconify-json/uil@1.2.1

**Comment by antfu** [comment] 2024-11-22 09:13
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-11-22 09:13 UTC

**Comment by buff** [comment] 2024-11-22 16:51
I think I worked out my problem... It's dynamic components... My implementation was vue based... I did not realise the nuance of how nuxt uses the resolver function. Anyway, will play with this some more but thought it might help somebody else...
