### ISSUE TITLE
Setting custom Component Name doesn't do anything.

### ISSUE THREAD

**Issue by ZackPlauche** [nuxt/icon#180] opened 2024-06-29 07:37 UTC
> Oh it's
> 
> ```ts
> export default defineNuxtConfig({
>   modules: [
>     'nuxt-icon',
>   ],
>   icon: {
>     componentName: 'NuxtIcon',
>   },
> })
> ```

Hi, so I just tried this but it still only appears when using `<Icon name="..." />` :|

Config:
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    "@nuxtjs/tailwindcss",
    "@storyblok/nuxt",
    "nuxt-icon",
  ],
  icon: {
    componentName: 'NuxtIcon',
  },
})
```

_Originally posted by @ZackPlauche in https://github.com/nuxt/icon/issues/174#issuecomment-2192184553_

**Comment by danjrwalsh** [comment] 2024-07-08 02:23
@ZackPlauche Would you be able to provide a simple repro for this with StackBlitz or something similar? `icon.componentName` is working for me in my limited testing.

**Comment by antfu** [comment] 2024-07-15 15:42
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-15 15:42 UTC

**Comment by ZackPlauche** [comment] 2024-07-23 22:00
> @ZackPlauche Would you be able to provide a simple repro for this with StackBlitz or something similar? `icon.componentName` is working for me in my limited testing.

Hi sorry for late reply. I've personally never gotten StackBlitz to work so I wouldn't know how to set something up there 😅

**Comment by ZackPlauche** [comment] 2024-07-23 22:01
Update: It turns out I was using the old `nuxt-icon` instead of the new `@nuxt/icon`

**Comment by ZackPlauche** [comment] 2024-07-23 22:05
Wait, nope... that broke it. Are you guys using `componentName` or `componentNames`? TypeScript isn't giving me a `componentName`...
