### ISSUE TITLE
How to display exports

### ISSUE THREAD

**Issue by CooperJiang** [nuxt/icon#253] opened 2024-09-11 07:54 UTC
function renderIcon(name: string) {
  return () => {
    return h(Icon, { name })
  }
}

If the first parameter of the h function is used, how should it display the export

**Comment by antfu** [comment] 2024-09-11 08:15
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-09-11 08:15 UTC
