### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by YYCarl** [nuxt/icon#244] opened 2024-08-27 10:29 UTC
![22C047ADA668256DE33EF47C5493912C](https://github.com/user-attachments/assets/3b0f793e-4cfa-43ad-b112-34aa6292b960)

**Comment by antfu** [comment] 2024-08-27 10:33
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-27 10:33 UTC
