### ISSUE TITLE
Can't Build Production: error Command failed with signal "SIGKILL". on Update to 1.3.1

### ISSUE THREAD

**Issue by QaahirStewart** [nuxt/icon#215] opened 2024-07-24 02:26 UTC
My Vercel Build is Failing.

Getting this error when updating dependency. Moved from "@nuxt/icon": "1.2.0" to latest 1.3.1

error Command failed with signal "SIGKILL".

**Comment by QaahirStewart** [comment] 2024-07-24 02:41
Anything after 1.2.0 getting the error. tried with 1.2.1 and 1.3.0

**Comment by antfu** [comment] 2024-07-24 09:10
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-24 09:10 UTC
