### ISSUE TITLE
[BUG]: CSS mode causes DOMException

### ISSUE THREAD

**Issue by LeaderbotX400** [nuxt/icon#189] opened 2024-07-06 03:11 UTC
I don't have a whole lot of info for this issue other than when in `mode: 'css'` it spits out

```
Uncaught (in promise) DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
```

but `mode: 'svg'` works just fine

Its worth noting that the icons still render in CSS mode

**Comment by GeordiD** [comment] 2024-07-06 15:16
I am also seeing this, and moving to svg mode fixed it for me as well.

```vue
<Icon
  v-if="fooCondition"
  name="material-symbols:sync-outline"
  class="arrow-mixed"
/>
```

Details:
* Just installed the Icons module in this fairly basic nuxt project
* I do have the tailwind module installed in this project
* I tested whether or not applying a class to the icon component changed behavior related to this bug -- it did not.
* It seems to render fine server-side but crash during hydration. (new to Nuxt, so not sure that's right)
* When it breaks, I get a full screen error page

**Comment by danjrwalsh** [comment] 2024-07-07 15:05
I've created PR #192 which I believe may address this.

My guess is CORS-related errors caused by external stylesheets being injected by browser extensions or something similar.

**Comment by agracia-foticos** [comment] 2024-07-08 07:17
same issue!

**Closed** 2024-07-15 16:07 UTC
